///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SerachProductOnAmazon
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("ddbfefc3-6d81-4e1f-8672-264ec358a603", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SerachProductOnAmazonRepository repository.
        /// </summary>
        public static SerachProductOnAmazonRepository repo = SerachProductOnAmazonRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
            ClickOnElement = "1106;751";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _ClickOnElement;

        /// <summary>
        /// Gets or sets the value of variable ClickOnElement.
        /// </summary>
        [TestVariable("2b75b77d-0630-473c-8a3d-1e5f1c435fe6")]
        public string ClickOnElement
        {
            get { return _ClickOnElement; }
            set { _ClickOnElement = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Twotabsearchtextbox' at 175;39.", repo.ApplicationUnderTest.TwotabsearchtextboxInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Twotabsearchtextbox.Click("175;39");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'New Apple iPhone 12 Mini (64GB) - Blue' with focus on 'ApplicationUnderTest.Twotabsearchtextbox'.", repo.ApplicationUnderTest.TwotabsearchtextboxInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Twotabsearchtextbox.PressKeys("New Apple iPhone 12 Mini (64GB) - Blue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.NavSearchSubmitButton' at 21;33.", repo.ApplicationUnderTest.NavSearchSubmitButtonInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.NavSearchSubmitButton.Click("21;33");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest' at 1919;47.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Self.MoveTo("1919;47");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest' at 1919;47.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Self.MoveTo("1919;47");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 0;0.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.Self.Click("0;0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest' at 1919;47.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.Self.MoveTo("1919;47");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AddToCartButton' at 174;23.", repo.ApplicationUnderTest.AddToCartButtonInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.AddToCartButton.Click("174;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AddToCartButton' at 174;23.", repo.ApplicationUnderTest.AddToCartButtonInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.AddToCartButton.Click("174;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.NewAppleIPhone12Mini64GBBlue' at 235;23.", repo.ApplicationUnderTest.NewAppleIPhone12Mini64GBBlueInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.NewAppleIPhone12Mini64GBBlue.Click("235;23");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
