///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SerachProductOnAmazon
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SerachProductOnAmazonRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("0a9a4765-5722-4981-926c-918e49807ce5")]
    public partial class SerachProductOnAmazonRepository : RepoGenBaseFolder
    {
        static SerachProductOnAmazonRepository instance = new SerachProductOnAmazonRepository();
        SerachProductOnAmazonRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        SerachProductOnAmazonRepositoryFolders.P3CLAPF1W4AFHAppFolder _p3clapf1w4afh;

        /// <summary>
        /// Gets the singleton class instance representing the SerachProductOnAmazonRepository element repository.
        /// </summary>
        [RepositoryFolder("0a9a4765-5722-4981-926c-918e49807ce5")]
        public static SerachProductOnAmazonRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SerachProductOnAmazonRepository() 
            : base("SerachProductOnAmazonRepository", "/", null, 0, false, "0a9a4765-5722-4981-926c-918e49807ce5", ".\\RepositoryImages\\SerachProductOnAmazonRepository0a9a4765.rximgres")
        {
            _applicationundertest = new SerachProductOnAmazonRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _p3clapf1w4afh = new SerachProductOnAmazonRepositoryFolders.P3CLAPF1W4AFHAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("0a9a4765-5722-4981-926c-918e49807ce5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("031f3934-ae17-424e-8bd7-87a196792419")]
        public virtual SerachProductOnAmazonRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The P3CLAPF1W4AFH folder.
        /// </summary>
        [RepositoryFolder("21478a05-c1bf-460f-a183-b5dd69db9b61")]
        public virtual SerachProductOnAmazonRepositoryFolders.P3CLAPF1W4AFHAppFolder P3CLAPF1W4AFH
        {
            get { return _p3clapf1w4afh; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class SerachProductOnAmazonRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("031f3934-ae17-424e-8bd7-87a196792419")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _downloadtheamazonappInfo;
            RepoItemInfo _asectionaspacingnonegwcardlayoutInfo;
            RepoItemInfo _twotabsearchtextboxInfo;
            RepoItemInfo _navsearchsubmitbuttonInfo;
            RepoItemInfo _ascrollerascrollerverticalewcscrolInfo;
            RepoItemInfo _centercolInfo;
            RepoItemInfo _addtocartbuttonInfo;
            RepoItemInfo _newappleiphone12mini64gbblueInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.amazon.in']", parentFolder, 30000, null, false, "031f3934-ae17-424e-8bd7-87a196792419", "")
            {
                _downloadtheamazonappInfo = new RepoItemInfo(this, "DownloadTheAmazonApp", ".//div[#'gw-card-layout']/div[4]//a[@innertext='Download the Amazon App']", "", 30000, null, "b14dc429-f3cb-47c6-914b-3371017b41fe");
                _asectionaspacingnonegwcardlayoutInfo = new RepoItemInfo(this, "ASectionASpacingNoneGwCardLayout", ".//div[#'gw-card-layout']/div[4]", "", 30000, null, "a87474c3-fad6-4c26-b558-8c85148b449c");
                _twotabsearchtextboxInfo = new RepoItemInfo(this, "Twotabsearchtextbox", ".//input[#'twotabsearchtextbox']", "", 30000, null, "dddc04e6-3371-46be-b6d4-370c00532da9");
                _navsearchsubmitbuttonInfo = new RepoItemInfo(this, "NavSearchSubmitButton", ".//input[#'nav-search-submit-button']", "", 30000, null, "2dbb29f0-08f4-425a-ba6b-01758a36b8bf");
                _ascrollerascrollerverticalewcscrolInfo = new RepoItemInfo(this, "AScrollerAScrollerVerticalEwcScrol", ".//div[#'ewc-compact-body']/div", "", 30000, null, "1460d56d-f271-44f0-9b80-88791c907f17");
                _centercolInfo = new RepoItemInfo(this, "CenterCol", ".//div[#'search']/div[1]/div[2]/div/span[3]/div[2]/div[4]/?/?/span/div/div/div[2]/div[2]/div/div[1]//a[@href>'https://www.amazon.in/New']/span[@innertext>'New Apple iPhone 12 (128GB)' and @title=null()]", "", 30000, null, "c7178d3e-31fa-40ef-a0ad-333198d88b3e");
                _addtocartbuttonInfo = new RepoItemInfo(this, "AddToCartButton", ".//input[#'add-to-cart-button']", "", 30000, null, "bb26a777-1cf4-467b-926d-9c2b3250be33");
                _newappleiphone12mini64gbblueInfo = new RepoItemInfo(this, "NewAppleIPhone12Mini64GBBlue", ".//div[#'search']/div[1]/div[2]/div/span[3]/div[2]/div[3]/?/?/span/div/div/div[2]/div[2]/div/div[1]//a[@href>'https://www.amazon.in/New']/span[@innertext>'New Apple iPhone 12 Mini (64GB)']", "", 30000, null, "facd8b44-6e4f-42ff-b1bf-0900ce64300e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("031f3934-ae17-424e-8bd7-87a196792419")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("031f3934-ae17-424e-8bd7-87a196792419")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DownloadTheAmazonApp item.
            /// </summary>
            [RepositoryItem("b14dc429-f3cb-47c6-914b-3371017b41fe")]
            public virtual Ranorex.ATag DownloadTheAmazonApp
            {
                get
                {
                    return _downloadtheamazonappInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The DownloadTheAmazonApp item info.
            /// </summary>
            [RepositoryItemInfo("b14dc429-f3cb-47c6-914b-3371017b41fe")]
            public virtual RepoItemInfo DownloadTheAmazonAppInfo
            {
                get
                {
                    return _downloadtheamazonappInfo;
                }
            }

            /// <summary>
            /// The ASectionASpacingNoneGwCardLayout item.
            /// </summary>
            [RepositoryItem("a87474c3-fad6-4c26-b558-8c85148b449c")]
            public virtual Ranorex.DivTag ASectionASpacingNoneGwCardLayout
            {
                get
                {
                    return _asectionaspacingnonegwcardlayoutInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ASectionASpacingNoneGwCardLayout item info.
            /// </summary>
            [RepositoryItemInfo("a87474c3-fad6-4c26-b558-8c85148b449c")]
            public virtual RepoItemInfo ASectionASpacingNoneGwCardLayoutInfo
            {
                get
                {
                    return _asectionaspacingnonegwcardlayoutInfo;
                }
            }

            /// <summary>
            /// The Twotabsearchtextbox item.
            /// </summary>
            [RepositoryItem("dddc04e6-3371-46be-b6d4-370c00532da9")]
            public virtual Ranorex.InputTag Twotabsearchtextbox
            {
                get
                {
                    return _twotabsearchtextboxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Twotabsearchtextbox item info.
            /// </summary>
            [RepositoryItemInfo("dddc04e6-3371-46be-b6d4-370c00532da9")]
            public virtual RepoItemInfo TwotabsearchtextboxInfo
            {
                get
                {
                    return _twotabsearchtextboxInfo;
                }
            }

            /// <summary>
            /// The NavSearchSubmitButton item.
            /// </summary>
            [RepositoryItem("2dbb29f0-08f4-425a-ba6b-01758a36b8bf")]
            public virtual Ranorex.InputTag NavSearchSubmitButton
            {
                get
                {
                    return _navsearchsubmitbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The NavSearchSubmitButton item info.
            /// </summary>
            [RepositoryItemInfo("2dbb29f0-08f4-425a-ba6b-01758a36b8bf")]
            public virtual RepoItemInfo NavSearchSubmitButtonInfo
            {
                get
                {
                    return _navsearchsubmitbuttonInfo;
                }
            }

            /// <summary>
            /// The AScrollerAScrollerVerticalEwcScrol item.
            /// </summary>
            [RepositoryItem("1460d56d-f271-44f0-9b80-88791c907f17")]
            public virtual Ranorex.DivTag AScrollerAScrollerVerticalEwcScrol
            {
                get
                {
                    return _ascrollerascrollerverticalewcscrolInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The AScrollerAScrollerVerticalEwcScrol item info.
            /// </summary>
            [RepositoryItemInfo("1460d56d-f271-44f0-9b80-88791c907f17")]
            public virtual RepoItemInfo AScrollerAScrollerVerticalEwcScrolInfo
            {
                get
                {
                    return _ascrollerascrollerverticalewcscrolInfo;
                }
            }

            /// <summary>
            /// The CenterCol item.
            /// </summary>
            [RepositoryItem("c7178d3e-31fa-40ef-a0ad-333198d88b3e")]
            public virtual Ranorex.SpanTag CenterCol
            {
                get
                {
                    return _centercolInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CenterCol item info.
            /// </summary>
            [RepositoryItemInfo("c7178d3e-31fa-40ef-a0ad-333198d88b3e")]
            public virtual RepoItemInfo CenterColInfo
            {
                get
                {
                    return _centercolInfo;
                }
            }

            /// <summary>
            /// The AddToCartButton item.
            /// </summary>
            [RepositoryItem("bb26a777-1cf4-467b-926d-9c2b3250be33")]
            public virtual Ranorex.InputTag AddToCartButton
            {
                get
                {
                    return _addtocartbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AddToCartButton item info.
            /// </summary>
            [RepositoryItemInfo("bb26a777-1cf4-467b-926d-9c2b3250be33")]
            public virtual RepoItemInfo AddToCartButtonInfo
            {
                get
                {
                    return _addtocartbuttonInfo;
                }
            }

            /// <summary>
            /// The NewAppleIPhone12Mini64GBBlue item.
            /// </summary>
            [RepositoryItem("facd8b44-6e4f-42ff-b1bf-0900ce64300e")]
            public virtual Ranorex.SpanTag NewAppleIPhone12Mini64GBBlue
            {
                get
                {
                    return _newappleiphone12mini64gbblueInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The NewAppleIPhone12Mini64GBBlue item info.
            /// </summary>
            [RepositoryItemInfo("facd8b44-6e4f-42ff-b1bf-0900ce64300e")]
            public virtual RepoItemInfo NewAppleIPhone12Mini64GBBlueInfo
            {
                get
                {
                    return _newappleiphone12mini64gbblueInfo;
                }
            }
        }

        /// <summary>
        /// The P3CLAPF1W4AFHAppFolder folder.
        /// </summary>
        [RepositoryFolder("21478a05-c1bf-460f-a183-b5dd69db9b61")]
        public partial class P3CLAPF1W4AFHAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _p3clapf1w4afhInfo;

            /// <summary>
            /// Creates a new P3CLAPF1W4AFH  folder.
            /// </summary>
            public P3CLAPF1W4AFHAppFolder(RepoGenBaseFolder parentFolder) :
                    base("P3CLAPF1W4AFH", "", parentFolder, 30000, null, true, "21478a05-c1bf-460f-a183-b5dd69db9b61", "")
            {
                _p3clapf1w4afhInfo = new RepoItemInfo(this, "P3CLAPF1W4AFH", "", "", 30000, null, "ff1dd1e8-2e83-4210-98b4-ecbfe1e03759");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("21478a05-c1bf-460f-a183-b5dd69db9b61")]
            public virtual Ranorex.Host Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Host>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("21478a05-c1bf-460f-a183-b5dd69db9b61")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The P3CLAPF1W4AFH item.
            /// </summary>
            [RepositoryItem("ff1dd1e8-2e83-4210-98b4-ecbfe1e03759")]
            public virtual Ranorex.Host P3CLAPF1W4AFH
            {
                get
                {
                    return _p3clapf1w4afhInfo.CreateAdapter<Ranorex.Host>(true);
                }
            }

            /// <summary>
            /// The P3CLAPF1W4AFH item info.
            /// </summary>
            [RepositoryItemInfo("ff1dd1e8-2e83-4210-98b4-ecbfe1e03759")]
            public virtual RepoItemInfo P3CLAPF1W4AFHInfo
            {
                get
                {
                    return _p3clapf1w4afhInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
